title: Terrance Luangrath
logo: /assets/img/headshot.png
description: Graduate Data Science student showcasing projects in machine learning, optimization, and data visualization using Python, R, and real-world datasets.
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
