title: Terrance Luangrath
logo: /assets/img/headshot_circle.png
description: Graduate Data Science student showcasing projects in machine learning, optimization, and data visualization using Python, R, and real-world datasets.

remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    block:
      mermaid: true
